"""first change

Revision ID: c11a1c0371b1
Revises: 
Create Date: 2021-08-23 19:28:36.107875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c11a1c0371b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mass_details',
    sa.Column('mass_no', sa.Integer(), nullable=False),
    sa.Column('total_seat', sa.Integer(), nullable=True),
    sa.Column('remainig_seat', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('mass_no')
    )
    op.create_table('massbook',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=55), nullable=True),
    sa.Column('time', sa.String(length=55), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('h_name', sa.String(length=80), nullable=True),
    sa.Column('mobile', sa.Integer(), nullable=True),
    sa.Column('mass_no', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('book_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('massbook')
    op.drop_table('mass_details')
    # ### end Alembic commands ###
